name: Publish on Modrinth & GitHub

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  JAVA_VERSION: 17
  VERSION: 1.1.0
  RELEASE_NAME: TP Chat Command 1.1.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "microsoft"

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: xpCSAwvb
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-tag: "v${{ env.VERSION }}"
          github-token: ${{ secrets.TPCHAT_PUBLISH_TOKEN }}

          name: ${{ env.RELEASE_NAME }}
          version: ${{ env.VERSION }}
          version-type: release

          loaders: fabric
          java: ${{ env.JAVA_VERSION }}
          game-versions: |
            >=1.20
